# Generated by Django 3.1.2 on 2020-10-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('choice_1', models.CharField(max_length=30)),
                ('choice_2', models.CharField(max_length=30)),
                ('choice_3', models.CharField(max_length=30)),
                ('choice_1_count', models.IntegerField(default=0)),
                ('choice_2_count', models.IntegerField(default=0)),
                ('choice_3_count', models.IntegerField(default=0)),
            ],
        ),
    ]
